//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cartID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<int> productID { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<bool> savedForLater { get; set; }
        public Nullable<System.DateTime> timeAdded { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Product Product { get; set; }
    }
}
