//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderDetailsID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quntity { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<int> orderID { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
